<?php

namespace App\DataFixtures;

use App\Entity\Artist as EntityArtist;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class Artist extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $names = [
            'Aaron Boyd',
            'Aaron Forsythe',
            'Aaron J. Riley',
            'Aaron Miller',
            'Aaron Reed',
            'Abigail Larson',
            'Abz J Harding',
            'Adam Burn',
            'Adam Paquette',
            'Adam Rex',
            'Adam Vehige',
            'Adam Volker',
            'Adi Granov',
            'Adrian Majkrzak',
            'Adrián Rodríguez Pérez',
            'Adrian Smith',
            'Aenami',
            'Aeron Ng',
            'Ai Desheng',
            'Ai Nanahira',
            'Airi Yoshihisa',
            'akio',
            'AKQA',
            'Alan Pollack',
            'Alan Rabinowitz',
            'Alayna Danner',
            'AlbaBG',
            'Al Davidson',
            'Aldo Domínguez',
            'Alejandro Mirabal',
            'Aleksi Briclot',
            'Alessandra Pisano',
            'Alexander Forssberg',
            'Alexander Gering',
            'Alexander Khabbazi',
            'Alexander Kintner',
            'Alexander Mokhov',
            'Alexander Ostrowski',
            'Alexandre Breton',
            'Alexandre Chaudret',
            'Alexandre Honoré',
            'Alexandre Leoni',
            'Alexandr Leskinen',
            'Alex Brock',
            'Alex Dos Diaz',
            'Alexey Kruglov',
            'Alex Horley-Orlandelli',
            'Alexis Hernandez',
            'Alexis Ziritt',
            'Alex Konstad',
            'Alex Negrea',
            'Alex Petty',
            'Alex Stone',
            'Alex Tarca',
            'Alfven Ato',
            'Alice Xia Zhang',
            'Alicia Mickes',
            'Alina Marica',
            'Alisa Lee',
            'Alison Luhrs',
            'Alix Branwyn',
            'Aliya, age 5½',
            'Allen Douglas',
            'Allen Morris',
            'Allen Williams',
            'Allison Carl',
            'Alli Steele',
            'Alton Lawson',
            'Álvaro Calvo Escudero',
            'Amayagido',
            'A. M. Sartor',
            'Amy Weber',
            'Anastasia Balakchina',
            'Anastasia Ovchinnikova',
            'Anato Finnstark',
            'Andi Rusu',
            'Anditya Dita',
            'Andréa Blouin',
            'Andrea De Dominicis',
            'Andrea Piparo',
            'Andrea Radeck',
            'Andrea Sipl',
            'Andreas Rocha',
            'Andreas Zafiratos',
            'Andreia Ugrai',
            'Andrew Goldhawk',
            'Andrew Huerta',
            'Andrew MacLean',
            'Andrew Mar',
            'Andrew Murray',
            'Andrew Robinson',
            'Andrew Theophilopoulos',
            'Andrey Kuzinskiy',
            'Andrey Nyarl',
            'AndWorld Design',
            'Andy Brase',
            'Andy Williams',
            'Ângelo Bortolini',
            'Aniekan Udofia',
            'Anik Sikder',
            'Anna Christenson',
            'Anna Fehr',
            'Anna Mitura-Laskowska',
            'Anna Pavleeva',
            'Anna Podedworna',
            'Anna Steinbauer',
            'Annie Sardelis',
            'Ann-Sophie De Steur',
            'Anson Maddocks',
            'Anthony Devine',
            'Anthony Francisco',
            'Anthony Jones',
            'Anthony Palumbo',
            'Anthony S. Waters',
            'Antonio Bravo',
            'Antonio José Manzanedo',
            'Anton Solovianchyk',
            'Aogachou',
            'Apolo Cacho',
            'April Lee',
            'April Prime',
            'Arash Radkia',
            'Areku Nishiki',
            'Ari',
            'Ariel Olivetti',
            'Ariel Perez',
            'Arik Roper',
            'Ari Nieh',
            'Armand Baltazar',
            'Arnie Swekel',
            'Arthur Yuan',
            'Artur Nakhodkin',
            'Artur Treffner',
            'Ashlea Kelly',
            'Ashley Mackenzie',
            'Ash Wood',
            'Astri Lohne',
            'Atsushi Furusawa',
            'Audrey Benjaminsen',
            'Augusto Quirino',
            'Aurore Folny',
            'Austin Hsu',
            'Autumn Rain Turkel',
            'Awanqi (Angela Wang)',
            'Axel Sauerwald',
            'Aya Kakeda',
            'Aya Kato',
            'Ayako Ishiguro',
            'Ayami Kojima',
            'Ayami Nakashima',
            'Ayuko',
            'Azur',
            'Azutaro',
            'Babyson Chen',
            'Bad Flip Productions, Inc.',
            'Bakshi Productions',
            'Barbara Rosiak',
            'Barbara Witkowska',
            'Bardo Bread',
            'Barely Human',
            'Bartek Fedyczak',
            'Bartłomiej Gaweł',
            'Bastien Grivet',
            'Bastien L. Deharme',
            'Bayard Wu',
            'BBC Studios',
            'BD',
            'BEMOCS',
            'Bene Rohlmann',
            'Ben Hill',
            'Benjamin Ee',
            'Ben Maier',
            'Ben Schnuck',
            'Ben Thompson',
            'Ben Wootten',
            'Berry',
            'Betty Jiang',
            'Bill McConkey',
            'Bill Sienkiewicz',
            'Billy Christian',
            'Blackie del Rio',
            'BLUMOO',
            'Bob Eggleton',
            'Bob Petillo',
            'Bob Ross',
            'BODAX',
            'Boell Oyino',
            'Bogdan Marica',
            'Bogdan Rezunenko',
            'Boneface',
            'Bonnie Gabriel',
            'Border',
            'Borja Pindado',
            'Bradley Williams',
            'Brad Rigney',
            'Brain Dead',
            'Bram Sels',
            'Brandi Milne',
            'Brandi Reece',
            'Brandon Dorman',
            'Brandon Kitkouski',
            'Brandon L. Hunt',
            'Brendan Sell',
            'Brent Hollowell',
            'Brian Despain',
            'Brian Durfee',
            'Brian Hagan',
            'Brian Horton',
            'Brian Snõddy',
            'Brian Valeza',
            'Brigitte Roka',
            'Brittany Austin',
            'Brock Grossman',
            'Brom',
            'Brooklyn Smith',
            'BrooklynSnobs',
            'Bruce Brenneise',
            'Bruno Biazotto',
            'Bryan Sola',
            'Bryan Talbot',
            'Brynn Metheney',
            'Bryon Wackwitz',
            'Bud Cook',
            'Cabrol',
            'Caio E Santos',
            'Caio Monteiro',
            'Cai Tingting',
            'Calder Moore',
            'Camille Alquier',
            'Campbell White',
            'Canata Katana',
            'Caramelaw',
            'Cara Mitten',
            'Carissa Susilo',
            'Carl Critchlow',
            'Carl Frank',
            'Carlos Palma Cruchaga',
            'Carly Mazur',
            'Carmen Sinek',
            'Carol Azevedo',
            'Carol Heyer',
            'Caroline Gariba',
            'Casey Gustafson',
            'Casimir Lee',
            'CatDirty',
            'Catherine Buck',
            'Cecil Fernando',
            'Chad Kanotz',
            'Chad Weatherford',
            'Charles Gillespie',
            'Charles Urbach',
            'Chase Stone',
            'Chen Weidong',
            'Chippy',
            'chiri*',
            'Chong Fei Giap',
            'Chris Appelhans',
            'Chris Bellach',
            'Chris Clay',
            'Chris Cold',
            'Chris Dien',
            'Chris Haukap',
            'Chris J. Anderson',
            'Chris Kiritz',
            'Chris Mooney',
            'Chris Ostrowski',
            'Chris Rahn',
            'Chris Rallis',
            'Chris Seaman',
            'Christian Angel',
            'Christian Dimitrov',
            'Christina Davis',
            'Christina Kraus',
            'Christine Choi',
            'Christine Couture',
            'Christine Lee Risinger',
            'Christopher Burdett',
            'Christopher Lovell',
            'Christopher Moeller',
            'Christopher Rush',
            'Chris Tulach',
            'Chuck Grieb',
            'Chuck Lukacs',
            'Chun Lo',
            'Ciruelo',
            'Clare Wong',
            'Claudiu-Antoniu Magherusan',
            'Cliff Childs',
            'Cliff Nielsen',
            'Clint Cearley',
            'Clint Langley',
            'Clint Lockwood',
            'Clover.K',
            'Clyde Caldwell',
            'Cody Culp',
            'Cole Eastburn',
            'Colin Boyer',
            'Colin MacNeil',
            'Collin Estrada',
            'Constantin Marin',
            'Corey Bowen',
            'Corey D. Macourek',
            'Cornelius Brudi',
            'Cory Godbey',
            'Cory Trego-Erdner',
            'Cos Koniotis',
            'Cosmin Podar',
            'Craig Elliott',
            'Craig Hooper',
            'Craig J Spearing',
            'Craig Mullins',
            'Cris Dornaus',
            'Cristi Balanescu',
            'Crocodile Jackson',
            'CROM',
            'Crystal Sully',
            'Cynthia Sheppard',
            'Cyril Van Der Haegen',
            'Daarken',
            'Daisuke Izuka',
            'Daisuke Tatsuma',
            'Dai-XT',
            'Daken',
            'D. Alexander Gregory',
            'Dallas Williams',
            'Dalton Pencarinha',
            'Dameon Willich',
            'Damian Tedrow',
            'Dana Knutson',
            'Dan Dos Santos',
            'Daneen Wilkerson',
            'Dan Frazier',
            'Daniel Correia',
            'Daniel Gelon',
            'Daniel Holt',
            'Daniel Ketchum',
            'Daniel Lieske',
            'Daniel Ljunggren',
            'Daniel R. Horne',
            'Daniel Romanovsky',
            'Daniel Warren Johnson',
            'Daniel Zrom',
            'Dani Pendergast',
            'Dan Mumford',
            'Dan Murayama Scott',
            'Danny Miller',
            'Danny Schwartz',
            'Dan Seagrave',
            'Dan Watson',
            'Dany Orizio',
            'Darbury Stenderu',
            'Darek Zabrocki',
            'Daren Bader',
            'Daria Aksenova',
            'Daria Khlebnikova',
            'Darrell Riche',
            'Darren Tan',
            'Dave Allsop',
            'Dave DeVries',
            'Dave Dorman',
            'Dave Geyer',
            'Dave Greco',
            'Dave Humpherys',
            'Dave Kendall',
            'Dave Trampier',
            'David A. Cherry',
            'David Álvarez',
            'David Astruga',
            'David Auden Nash',
            'David Borba',
            'David Curtis',
            'David Day',
            'David Frasheski',
            'David Gaillet',
            'David Giraud',
            'David Ho',
            'David Horne',
            'David Hudnut',
            'David Martin',
            'David McDarby',
            'David Monette',
            'David O\'Connor',
            'David Palumbo',
            'David Petersen',
            'David Rapoza',
            'David Robert Hovey',
            'David Seeley',
            'David Seguin',
            'David Semple',
            'David Sladek',
            'David Sondered',
            'David Szabo',
            'Davor Gromilović',
            'Death Burger',
            'Demitrios Feredinos',
            'Denis Medri',
            'Denis Nigmatullin',
            'Denis Zhbankov',
            'Denman Rooke',
            'Dennis Detwiller',
            'Denys Tsiperko',
            'Dermot Power',
            'Deruchenko Alexander',
            'Desmuncubic',
            'Deven Rue',
            'Devin Platts',
            'Diana Cearley',
            'Diana Vick',
            'Dibujante Nocturno',
            'Diego Andrade',
            'Diego Gisbert',
            'Diesel',
            'Dimitar Marinski',
            'Ding Songjian',
            'DiTerlizzi',
            'D. J. Cleland-Hura',
            'Dmitriy Mironov',
            'Dmitry Burmak',
            'Dom!',
            'Domco.',
            'Domenico Cava',
            'Dominick Domingo',
            'Dominik Mayer',
            'Donato Giancola',
            'Don Hazeltine',
            'Don Thompson',
            'Doodleskelly',
            'Doug Chaffee',
            'Doug Keith',
            'Douglas Shuler',
            'Drew Baker',
            'Drew Moss',
            'Drew Tucker',
            'D-suzuki',
            'Durion',
            'DXTR',
            'Dylan Martens',
            'DZO',
            'Ebila',
            'Eddie Mendoza',
            'Eddie Schillo',
            'Edgar Sánchez Hidalgo',
            'Ed Repka',
            'Eduardo Francisco',
            'Edward P. Beard, Jr.',
            'Eelis Kyttanen',
            'Efflam Mercier',
            'Efrem Palacios',
            'Eilene Cherie',
            'Ejiwa \'Edge\' Ebenebe',
            'Ekaterina Burmak',
            'Elektrodeko',
            'Eli, age 8',
            'Eliette Mitchell',
            'Eli Minaya',
            'Eli Shiffrin',
            'Elizabeth Peiró',
            'Eliz Roxs',
            'ELK64',
            'Ellie Livingston',
            'Elliot Stevens',
            'Ema Gaspar',
            'E. M. Gist',
            'Emily Maltby',
            'Emily Teng',
            'Emmanuel Shiu',
            'Emma Rios',
            'Emrah Elmasli',
            'Erica Williams',
            'Erica Yang',
            'Eric David Anderson',
            'Eric Deschamps',
            'Eric Fortune',
            'Eric Peterson',
            'Eric Polak',
            'Eric Velhagen',
            'Eric Wilkerson',
            'Erikas Perl',
            'Erin Vest',
            'Erion Makuo',
            'Ernanda Souza',
            'Erol Otus',
            'Esad Ribic',
            'Eshpur',
            'Esuthio',
            'Ethan Fleischer',
            'Eugene Frost',
            'Eva Eskelinen',
            'Evan Cagle',
            'Evan Shipard',
            'Even Amundsen',
            'Evyn Fong',
            'Eytan Zana',
            'Ezoi',
            'Fajareka Setiawan',
            'Fang Xinyu',
            'Fang Yue',
            'Fariba Khamseh',
            'Fay Dalton',
            'Fay Jones',
            'Feifei Ruan',
            'Felipe Martini',
            'Fesbra',
            'Filip Burburan',
            'Filipe Pagliuso',
            'Finnian MacManus',
            'Fiona Hsieh',
            'Fiona Staples',
            'Flavio Girón',
            'Florey',
            'Florian Bertmer',
            'Florian de Gesincourt',
            'Florin Petre Bostan',
            'Foo Midori',
            'Forrest Imel',
            'Forrest Schehl',
            'Francesca Baerald',
            'Francesca Resta',
            'Francisco Badilla',
            'Francisco Martin',
            'Francisco Miyara',
            'Francis Tneh',
            'Francis Tsai',
            'Francois Dery',
            'Franco Tempesta',
            'Francoyovich',
            'Frank Frazetta',
            'Frank Kelly Freas',
            'Franz Vohwinkel',
            'Fred Fields',
            'Fred Harper',
            'Fred Hooper',
            'Fred Rahmqvist',
            'Fukuzo Katsura',
            'Fuzichoco',
            'Gaboleps',
            'Gabor Szikszai',
            'Gabriela Birchal',
            'Gabriel Tanko',
            'Gaga Zeng',
            'Gage Lindsten',
            'Galen Dara',
            'Games Workshop',
            'Gao Jianzhang',
            'Gao Yan',
            'Gary Baseman',
            'Gary Gianni',
            'Gary Leach',
            'Gary Ruddell',
            'Gavin Verhey',
            'Geofrey Darrow',
            'George Fan',
            'George Pratt',
            'Gerry Grace',
            'G-host Lee',
            'Giacomo Galloni',
            'Gina Matarazzo',
            'Gintas Galvanauskas',
            'Glen Angus',
            'Glenn Fabry',
            'Glenn Jones',
            'GodMachine',
            'Gomzé',
            'Gonçalo Pereira',
            'Goran Josic',
            'Gossip Goblin',
            'Gou Tanabe',
            'Gozz',
            'Grady Frederick',
            'Graeme Hopkins',
            'GrafitArt',
            'Graham Yarrington',
            'Grant Griffin',
            'Greg Bell',
            'Greg Bobrowski',
            'Greg Hildebrandt',
            'Greg Opalinski',
            'Greg Simanson',
            'Greg Spalenka',
            'Greg Staples',
            'Grzegorz Rutkowski',
            'Guga Baraldi',
            'Hagiya Kaoru',
            'Haku Tatsufuchi',
            'Halil Ural',
            'Hank Reavis',
            'Hannibal King',
            'Hanspeter Ziegler',
            'Hari & Deepti',
            'Harold McNeill',
            'Harpreet Rattan',
            'Harry Conway',
            'Hatori Kyoka',
            'Heather Hudson',
            'Hector Ortiz',
            'Heiko Mueller',
            'He Jiancheng',
            'Helge C. Balzer',
            'Hélio Frazão',
            'Helvetica Blanc',
            'Hendry Iwanaga',
            'Henry G. Higginbotham',
            'Henry Peters',
            'Henry Van Der Linde',
            'Heonhwa Choe',
            'Hideaki Takamura',
            'Hillary Wilson',
            'Hiro Izawa',
            'Hirokorin',
            'Hiromu',
            'Hiro Suda',
            'Hiro Usuda',
            'Hisashi Momose',
            'Hitowa',
            'Hongtae Taecholarn',
            'Hong Yan',
            'Howard Lyon',
            'Hozan Shinomaru',
            'Hristo D. Chukov',
            'Huang Qishi',
            'Hugh Jamieson',
            'Hung Nguy',
            'Hyan Tran, age 6',
            'Iain McCaig',
            'Ian Edward Ameling',
            'Ian Jepson',
            'Ian Miller',
            'Ichiko Milk Tei',
            'Iga Oliwiak',
            'Ignatius Budi',
            'Ignis Bruno',
            'Igor Grechanyi',
            'Igor Kieryluk',
            'Igor Krstic',
            'Iinuma Yuuki',
            'I☆LA',
            'Ilker Yildiz',
            'Illustranesia',
            'Ilse Gort',
            'Ina Wong',
            'Indra Nugroho',
            'Inka Schulz',
            'Inkognit',
            'Inoue Junichi',
            'Inuchiyo Meimaru',
            'Ioan Dumitrescu',
            'Ioannis Fiore',
            'Ionomycin',
            'I. Rabarot',
            'Ira Humphrey',
            'Irina Nordsol',
            'Iris Compiet',
            'Ironbrush',
            'Irvin Rodriguez',
            'Ishikawa Kenta',
            'Isis',
            'Issei Murakami',
            'Ittoku',
            'Ivan Dedov',
            'Ivan Shavrin',
            'Izumi Tomoki',
            'Izzy',
            'Jabari Weathers',
            'Jack Hughes',
            'Jackson Epstein',
            'Jack Teagle',
            'Jack Wang',
            'Jack Wei',
            'Jacob Nourigat',
            'Jacques Bredy',
            'Jade Granger',
            'Jae Lee',
            'Jaime A. Zuverza',
            'Jaime Jones',
            'Jair Medina',
            'Jake Murray',
            'Jakob Eirich',
            'Jakub Kasper',
            'Jakub Rebelka',
            'Jama Jurabaev',
            'James Allen',
            'James Arnold',
            'James Bernardin',
            'James Bousema',
            'James Ernest',
            'James Kei',
            'James Kooi',
            'James Paick',
            'James Rose',
            'James Ryman',
            'James Wong',
            'James Zapata',
            'Jamroz Gary',
            'Jana Schirmer',
            'Janet Aulisio',
            'Janine Johnston',
            'Jared Blando',
            'Jarel Threat',
            'Jaroslav Kosmina',
            'Jarreau Wimberly',
            'Jason A. Engle',
            'Jason Alexander Behnke',
            'Jason Chan',
            'Jason Felix',
            'Jason Kang',
            'Jason Li',
            'Jason Rainville',
            'Jason Smith',
            'Jasper Sandner',
            'Javier Charro',
            'Jay Ryan',
            'JB Casacop',
            'jD',
            'Jean-Christophe Drolet',
            'Jeanne D\'Angelo',
            'Jeannie L Paske',
            'Jean-Sébastien Rossbach',
            'Jedd Chevrier',
            'Jeff A. Menges',
            'Jeff Carpenter',
            'Jeff Dee',
            'Jeff Easley',
            'Jeff Laubenstein',
            'Jeff Miracola',
            'Jeff Nentrup',
            'Jeff Reitz',
            'Jeff Remmer',
            'Jeffrey R. Busch',
            'Jeff Simpson',
            'Jeff Soto',
            'Jeff Stewart',
            'Jehan Choo',
            'Jen Bartel',
            'Jennie Kim',
            'Jennifer Law',
            'Jennifer L. Meyer',
            'Jen Page',
            'Jérémie Solomon',
            'Jeremy Enecio',
            'Jeremy Jarvis',
            'Jeremy Paillotin',
            'Jeremy Wilson',
            'Jermaine Rogers',
            'Jerry Tiritilli',
            'Jesper Ejsing',
            'Jesper Myrfors',
            'Jesse LeDoux',
            'Jessica Rossier',
            'Jessica Seamans',
            'Jessie Lam',
            'Jiachen Tao',
            'Jiaming',
            'Jiang Zhuqing',
            'JiHun Lee',
            'Jim Murray',
            'Jim Nelson',
            'Jim Pavelec',
            'Jinho Bae',
            'Jintetsu',
            'Ji Yong',
            'J.Lonnee',
            'Joana LaFuente',
            'Joao Ruas',
            'Jock',
            'Jodie Muir',
            'Jody Clark',
            'Joe Esposito',
            'Joel Biske',
            'Joel Thomas',
            'Joe Slucher',
            'Joe Torra',
            'Johan Grenier',
            'Johann Bodin',
            'Johannes Mücke',
            'Johannes Voss',
            'John Avon',
            'John Bolton',
            'John Coulthart',
            'John Darnielle',
            'John Di Giovanni',
            'John Donahue',
            'John F. Malta',
            'John Franklin Howe',
            'John Gallagher',
            'John Howe',
            'John Malloy',
            'John Matson',
            'John Penick',
            'John Severin Brassell',
            'John Silva',
            'John Stanko',
            'John Tedrick',
            'John Thacker',
            'John Zeleznik',
            'Jokubas Uogintas',
            'Jonas De Ro',
            'Jonathan Kuo',
            'Jon Foster',
            'Jon J Muth',
            'Jon Juarez',
            'Jon Neimeister',
            'Jon Vermilyea',
            'Jordan Speer',
            'Jorge Gutierrez Garcia',
            'Jorge Jacinto',
            'Jose Cabrera',
            'José Parodi',
            'Joseph Meehan',
            'Joseph Weston',
            'Josh Corpuz',
            'Josh Hass',
            'Josh Newton',
            'Josh Thomas',
            'Joshua Alvarado',
            'Joshua Cairos',
            'Joshua Hagler',
            'Joshua Howard',
            'Joshua Raphael',
            'Josiah \'Jo\' Cameron',
            'Josu Hernaiz',
            'Josu Solano',
            'Joy Ang',
            'JOZ',
            'J.P. Targete',
            'JRZ251',
            'Jubilee',
            'Julia Griffin',
            'Julia Metzger',
            'Julian Kok Joon Wen',
            'Julia Vasilyeva',
            'Julie Baroh',
            'Julie Bell',
            'Julie Dillon',
            'Julio Reyna',
            'Jul Quanouai',
            'Jung Park',
            'JungShan',
            'Junior Tomlin',
            'Junji Ito',
            'Junko Taguchi',
            'Jurijus Chitrovas',
            'Justin Cornell',
            'Justine Cruz',
            'Justine Jones',
            'Justine Mara Andersen',
            'Justin Gerard',
            'Justin Hampton',
            'Justin Hernandez',
            'Justin Murray',
            'Justin Norman',
            'Justin Sweet',
            'Justyna Dura',
            'J. W. Frost',
            'Kai Carpenter',
            'Kaida Yuji',
            'Kaitlyn McCulley',
            'Kaja Foglio',
            'Kamila Szutenberg',
            'Kang Yu',
            'Kaoru Yukishiro',
            'Karen Hallion',
            'Kari Christensen',
            'Kari Johnson',
            'Karla Ortiz',
            'Karl Kopinski',
            'Karmazid',
            'Karuta Shiki',
            'Kasia \'Kafis\' Zielińska',
            'Katerina Ladon',
            'Kathleen Neeley',
            'Kathryn Rathke',
            'Katie Allison',
            'Kato Ayaka',
            'Kawasumi',
            'Kee Lo',
            'Keiji Hida',
            'Keith Garletts',
            'Keith Parkinson',
            'Kekai Kotaki',
            'Kelly Hamilton',
            'Kelly McBride',
            'Kelogsloops',
            'Kemonomichi',
            'Ken Meyer, Jr.',
            'Ken Nagle',
            'Kensuke Okabayashi',
            'Kento Matsuura',
            'KERA',
            'Kerby Rosanes',
            'Kerstin Kaman',
            'Kev Brockschmidt',
            'Kev Fang',
            'Kevin Dobler',
            'Kevin Dubell',
            'Kevin Gnutzmans',
            'Kevin McCann',
            'Kevin Murphy',
            'Kevin Sidharta',
            'Kevin Soler',
            'Kevin Yee',
            'Kev Walker',
            'Khang Le',
            'Khurrum',
            'Kieran Yanner',
            'Kim Dingwall',
            'Kimonas Theodossiou',
            'Kim Sokol',
            'Kipling West',
            'Kira, age 5½',
            'Kiritada',
            'Kirsten Zirngibl',
            'Kisung Koh',
            'Kitt Lapeña',
            'KIYA',
            'kleinerHai',
            'KNIIO',
            'Kogan',
            'Kohei Hayama',
            'Koji',
            'Koji Nishino',
            'Konstantin Porubov',
            'Kotakan',
            'Kota Nakatsubo',
            'kozyndan',
            'Krharts',
            'Kristen Bishop',
            'Kristina Carroll',
            'Kristina Collantes',
            'Kuang Sheng',
            'Kukka',
            'Kunio Hagio',
            'Kuregure',
            'kutay',
            'Ku Xueming',
            'Lack',
            'LA Draws',
            'Lake Hurwitz',
            'Lander Strijbol',
            'Larissa Hasenheit',
            'Larry Elmore',
            'Larry MacDougall',
            'Lars Grant-West',
            'Laura Plansker',
            'Laurel Austin',
            'Lauren K. Cannon',
            'Lauren YS',
            'Lawrence Snelly',
            'Laynes',
            'Leanna Crossan',
            'LeDania',
            'Leesha Hannigan',
            'Lena Zykova',
            'Lenka Šimečková',
            'Leonardo Borazio',
            'Leonardo Santanna',
            'Leon Tukker',
            'Leroy Steinmann',
            'Levi Parker',
            'Lē Yamamura',
            'LHQ',
            'Liam Sharp',
            'Liangliang Zhang',
            'Lie Setiawan',
            'Liiga Smilshkalne',
            'Lindsey Look',
            'Lin Yan',
            'Lisa Heidhoff',
            'Li Tie',
            'Liu Jianjian',
            'Liu Shangying',
            'Lius Lasahido',
            'Livia Prima',
            'Li Wang',
            'Li Xiaohua',
            'Lixin Yin',
            'Li Youliang',
            'Li Yousong',
            'Liz Danforth',
            'Liz Leo',
            'L J Koh',
            'Logan Feliciano',
            'Loïc Canavaggia',
            'Lordigan',
            'Lorenzo Lanfranconi',
            'Lorenzo Mastroianni',
            'Lou Harrison',
            'Lubov',
            'Lucas Firmino',
            'Lucas Graciano',
            'Lucas Staniec',
            'Lucas Terryn',
            'Luca Zontini',
            'Lucio Parrillo',
            'Lucy Meaden',
            'Luisa J. Preissler',
            'Luis Esteves',
            'Lukas Litzsinger',
            'Luke Pearson',
            'Maaz Ali Khan',
            'Mab Graves',
            'Maciej Kuciara',
            'Maddie Julyk',
            'Madeline Boni',
            'Madison Mosley',
            'Mads Ahm',
            'Maekawa Yuichi',
            'Maël Ollivier-Henry',
            'Magali Villeneuve',
            'Magane Okuda',
            'Magnus Jansson',
            'Maihope',
            'Maiko Aoji',
            'Maiko Yoshizawa',
            'Mai Okuma',
            'Maji',
            'MAMEZAWA',
            'Mandy Jurgens',
            'Manuel Castañón',
            'Marc-André Dupont',
            'Marcela Bolívar',
            'Marcela Medeiros',
            'Marcelo Vignali',
            'Marc Fishman',
            'Marco Bucci',
            'Marco Dotti',
            'Marco Espinosa',
            'Marco Gorlei',
            'Marco Nelor',
            'Marco Teixeira',
            'Marco Wulfr',
            'Marc Simonetti',
            'Margaret Organ-Kean',
            'Maria Abagnale',
            'Mariah Tekulve',
            'Marianne Martin',
            'Maria Poliakova',
            'Maria Zolotukhina',
            'Marie Magny',
            'Marija Tiurina',
            'Marika Lord',
            'Marina Ortega Lorente',
            'Marion Kivits',
            'Marisa Oh',
            'Mark A. Nelson',
            'Mark Behm',
            'Mark Brill',
            'Mark Evans',
            'Mark Harrison',
            'Mark Heggen',
            'Mark Hyzer',
            'Mark L. Gottlieb',
            'Marko Manev',
            'Mark Poole',
            'Mark Price',
            'Mark Purvis',
            'Mark Riddick',
            'Mark Romanoski',
            'Mark Rosewater',
            'Mark Tedin',
            'Mark Winters',
            'Mark Zug',
            'Marlene Yui',
            'Marsha Rivera',
            'Marta Nael',
            'Martina Fačková',
            'Martin Ansin',
            'Martina Pilcerova',
            'Martin de Diego Sádaba',
            'Martin McKenna',
            'Martin Ontiveros',
            'Martin Wittfooth',
            'Maru Ferreira',
            'Mary Josberger',
            'Mary Kathryn Amiotte-Beaulieu',
            'Marzena Nereida Piwowar',
            'Massimilano Frezzato',
            'Massiveface',
            'Mateus Manhanini',
            'Mathias Kollros',
            'Matt Cavotta',
            'Matt Dixon',
            'Matteo Bassini',
            'Matteo Marjoram',
            'Matt Forsyth',
            'Matt Gaser',
            'Matthew D. Wilson',
            'Matthew G. Lewis',
            'Matthew Gregory',
            'Matthew Mitchell',
            'Matt Jukes',
            'Matt Smith',
            'Matt Stawicki',
            'Matt Stewart',
            'Matt Stikker',
            'Matt Tabak',
            'Matt Thompson',
            'Matt Warren',
            'Matt Zeilinger',
            'Mauricio Calle',
            'Maxilla',
            'Maxime Minard',
            'Maxim Kostin',
            'Max McCall',
            'Maxx Marshall',
            'McLean Kendree',
            'Meel Tamphanon',
            'Mélanie Bourgeois',
            'Melissa A. Benson',
            'Melissa DeTora',
            'Meris Mullaley',
            'Merlin G.G',
            'Meyoco',
            'Mia Boas',
            'Miao Aili',
            'Micah Epstein',
            'Michael Bruinsma',
            'Michael C. Hayes',
            'Michael Danza',
            'Michael Hutter',
            'Michael Koehler',
            'Michael Koelsch',
            'Michael Komarck',
            'Michael MacRae',
            'Michael Phillippi',
            'Michael Ryan',
            'Michael Sutfin',
            'Michael Walsh',
            'Michael Weaver',
            'Michael Whelan',
            'Micha Huigen',
            'Michal Ivan',
            'Michał Miłkowski',
            'Michele Giorgi',
            'Michele Parisi',
            'Michelle Esposito',
            'Mid',
            'MiDQN',
            'Miguel Mercado',
            'Miguel Sacristan',
            'Miho Midorikawa',
            'Mike Bierek',
            'Mike Burns',
            'Mike Demaine',
            'Mike Dringenberg',
            'Mike Franchina',
            'Mike Jordana',
            'Mike Kerr',
            'Mike Kimble',
            'Mike Ploog',
            'Mike Raabe',
            'Mike Sass',
            'Mike Uziel',
            'Mikio Masuda',
            'Miklós Ligeti',
            'Mila Pesic',
            'Miles Johnston',
            'Milivoj Ćeran',
            'Mina Jeon',
            'M I N A T O',
            'Mintautas Šukys',
            'Minttu Hynninen',
            'Min Yum',
            'Miranda Meeks',
            'Mirko Failoni',
            'Miro Petrov',
            'Misei Ito',
            'Mitch Cotie',
            'Mitchell Malloy',
            'Mitsuaki Sagiri',
            'Mitsuhiro Arita',
            'Miyaki Hajime',
            'Miyuki Aramaki',
            'M.Matsumoto',
            'Mohamed, age 4',
            'Mollie Harms',
            'Mónica Robles Corzo',
            'Monique Thirifay',
            'Monte Michael Moore',
            'Monztre',
            'Moopic',
            'Mr. Misang',
            'MSCHF',
            'Muhammad Firdaus',
            'Murakami Hisashi',
            'MURUGIAH',
            'M. W. Kaluta',
            'Nablange',
            'Nadezhda Tikhomirova',
            'Nadia Hurianova',
            'Nagano',
            'Nakamura8',
            'Nana Qi',
            'Naochika Morishita',
            'Naoki Saito',
            'Naomi Baker',
            'Nao Miyoshi',
            'Narendra Bintara Adi',
            'Natalie Andrewson',
            'Nataly Anderson',
            'Nathalie Hertz',
            'Nathan Ian Greene',
            'Nathaniel Himawan',
            'N.C. Winters',
            'Nelson Brown',
            'Nelson DeCastro',
            'NéNé Thomas',
            'Nephelomancer',
            'Nereida',
            'Néstor Ossandón Leal',
            'NIARK1',
            'Nicholas Elias',
            'Nicholas Gregory',
            'Nick Bartoletti',
            'Nic Klein',
            'Nick Percival',
            'Nick Southam',
            'Nico Delort',
            'Nicola Leonard',
            'Nicole Gustafsson',
            'Nijimaarc',
            'Nikolai Maslakov',
            'Nikola Matkovic',
            'Nils Hamm',
            'Nino Is',
            'Nino Vecia',
            'Noah Bradley',
            'Noah Thatcher',
            'Noki',
            'Norikatsu Miyoshi',
            'Nottsuo',
            'O-G Osahune',
            'Oiya Zhang',
            'Oleg Bulakh',
            'Oleg Shekhovtsov',
            'Oleksandr Kozachenko',
            'Olena Richards',
            'Olga Tereshenko',
            'Oliver Wetter',
            'Olivier Bernard',
            'Omaha Pérez',
            'Omar Rayyan',
            'Oriana Menendez',
            'Ori Toor',
            'Ørjan Ruttenborg Svendsen',
            'Oscar Camacho',
            'Ovidio Cartagena',
            'Pablo Mendoza',
            'Pablo Rivera',
            'Pace Wilder',
            'Paolo Parente',
            'Paolo Puggioni',
            'Pascal Blanché',
            'Pascal Quidault',
            'Pat Lee',
            'Pat Lewis',
            'Patrick Faricy',
            'Patrick Ho',
            'Patrick Kochakji',
            'Patrick Kuhlman',
            'Patrik Hell',
            'Paul Bonner',
            'Paul Chadwick',
            'Pauline Voss',
            'Paulius Daščioras',
            'Paul Jackson',
            'Paul Lee',
            'Paul Mafayon',
            'Paul Scott Canavan',
            'Pavel Kolomeyets',
            'Pedro Correa',
            'Pedro Maia',
            'Pedro Potier',
            'PE-nekoR',
            'Penguu',
            'Peo Michie',
            'Peter Bollinger',
            'Peter Diamond',
            'Peter Mohrbacher',
            'Peter Polach',
            'Pete Venters',
            'Pete White',
            'Phil Foglio',
            'Philip Helliwell',
            'Philip Straub',
            'Philip Tan',
            'Phillip Mosness',
            'Phill Simmer',
            'Phil Stone',
            'Phoebe Wahl',
            'Pierre Loyvet',
            'Pierre Raveneau',
            'Pig Hands',
            'PINDURSKI',
            'Piotr Dura',
            'Piotr Foksowicz',
            'Piotr Jabłoński',
            'Piyo',
            'Poison Project',
            'Pon Lee',
            'Post Malone',
            'Princess Hidir',
            'Psydrian',
            'Puddnhead',
            'Qianhao Ma',
            'Qiao Dafu',
            'Qi Baocheng',
            'Qin Jun',
            'Qistina Khalidah',
            'Qiu De En',
            'Quan Xuejun',
            'Quintin Gleim',
            'Quinton Hoover',
            'Qu Xin',
            'Rachel Turian',
            'Rachta Lin',
            'Racrufi',
            'Rafael Albuquerque',
            'Rafal Wechterowicz',
            'Rafater',
            'Raf Kayupov',
            'Raf Sarmento',
            'Raita Kazama',
            'Ralph Horsley',
            'Raluca Marinescu',
            'Ramazan Kazaliev',
            'Randis Albion',
            'Randy Asplund-Faith',
            'Randy Elliott',
            'Randy Gallegos',
            'Randy Vargas',
            'Raoul Vitale',
            'Raph Lomotan',
            'Ravenna Tran',
            'Ray Lago',
            'Raymond Bonilla',
            'Raymond Swanland',
            'Rebecca Guay',
            'Rebecca On',
            'Rebekah Lynn',
            'Reiko Murakami',
            'Rémi Jacquot',
            'Rhonda Libbey',
            'Rian Gonzales',
            'Ricardo Bessa',
            'Ricardo Cavolo',
            'Ricardo Diseño',
            'Richard Kane Ferguson',
            'Richard Luong',
            'Richard Sardinha',
            'Richard Suwono',
            'Richard Thomas',
            'Richard Whitters',
            'Richard Wright',
            'Rick Emond',
            'Rick Farrell',
            'Rick O\'Brien',
            'Rien.',
            'Rimas Valeikis',
            'Rinco.',
            'Rindo Karasuba',
            'Rio Krisma',
            'Riot Games',
            'rishxxv',
            'rk post',
            'Rob Alexander',
            'Robbie Trevino',
            'Roberta Ingranata',
            'Robert Bliss',
            'Robert Cornelius',
            'Robert J Schuster',
            'Roberto Gatto',
            'Robh Ruppel',
            'Robin Olausson',
            'Robot Chicken',
            'Rob Rey',
            'Rockey Chen',
            'Rogério Vilela',
            'Roger Raupp',
            'Romana Kendelic',
            'Roman Klonek',
            'Roman Kuteynikov',
            'Roman Tishenin',
            'Romas Kukalis',
            'Romiy',
            'Ron Brown',
            'Ron Chironna',
            'Ron Lemen',
            'Ron Spears',
            'Ron Spencer',
            'Ron Walotsky',
            'Rope Arrow',
            'Rorubei',
            'Rosemary Valero-O\'Connell',
            'Rovina Cai',
            'Rowynn Ellis',
            'Rudy Siswanto',
            'Ruiko Nakamura',
            'Runa I. Rosenberger',
            'Russell Lu',
            'Russ Nicholson',
            'Ruth Thompson',
            'Ruxing Gao',
            'Ryan Alexander Lee',
            'Ryan Barger',
            'Ryan Pancoast',
            'Ryan Printz',
            'Ryan Quickfall',
            'Ryanroro',
            'Ryan Valle',
            'Ryan Yee',
            'Ryo Kamei',
            'Ryota-H',
            'Ryota Murayama',
            'Rytis Sabaliauskas',
            'Ryuichi Sakuma',
            'Ryutei',
            'RYUTETSU',
            'Sachin Teng',
            'Sadboi',
            'Sage Coffey',
            'Said, age 6',
            'Sakura Tomo',
            'Salvatorre Zee Yazzie',
            'Sal Villagran',
            'Sam Burley',
            'Sam Chivers',
            'Sam Denmark',
            'Sam Guay',
            'Sam Hogg',
            'Sami Makkonen',
            'Sam McKenzie',
            'Sam Rowan',
            'Sam Stoddard',
            'Samuel Araya',
            'Samuele Bandini',
            'Samuel Perin',
            'Sam White',
            'Sam Wolfe Connelly',
            'Sam Wood',
            'Samy Halim',
            'Sandra Everingham',
            'Sandy Lee',
            'Sansyu',
            'Sarah Finnigan',
            'Sarah Keortge',
            'Sara Leal',
            'Sara Pitre-Dorocher',
            'Sara Winters',
            'Satoru Senda',
            'Scooter',
            'Scott Altmann',
            'Scott Bailey',
            'Scott Balmer',
            'Scott Buoncristiano',
            'Scott Chou',
            'Scott Hampton',
            'Scott Kirschner',
            'Scott M. Fischer',
            'Scott Murphy',
            'Scott Okumura',
            'Scott Van Essen',
            'Sean Mayovsky',
            'Sean McConnell',
            'Sean Murray',
            'Sean O\'Neil',
            'Sean Sevestre',
            'Sean Vo',
            'Sebastian Giacobino',
            'Seb McKinnon',
            'See Machine',
            'SENNSU',
            'SENSEN',
            'Serena Malyon',
            'Sergei Leoluch Panin',
            'Sergei Ryzhov',
            'Sergey Glushakov',
            'Sergio Cosmai',
            'Seseon Yoon',
            'Seth Conley',
            'Setor Fiadzigbey',
            'Seung Hoon Na',
            'Shafer Brown',
            'Shahab Alizadeh',
            'Shang Huitong',
            'Shawn Pagels',
            'Shawn Wood',
            'Shelly Wan',
            'Shie Nanahara',
            'Shikee',
            'Shinchuen Chen',
            'Shirai Hidemi',
            'Shiramine',
            'Shiro Yayoi',
            'Shishizaru',
            'Showichi Furumi',
            'Shreya Shetty',
            'Shuangcheng Leng',
            'Sidharth Chaturvedi',
            'Signalnoise',
            'Sija Hong',
            'Sila',
            'Simon Bisley',
            'Simon Dominic',
            'Skinner',
            'Skinnyelbows',
            'Slawomir Maniak',
            'SOFT_MEN',
            'Solomon Au Yeung',
            'Song Qijin',
            'Song Shikai',
            'Sophie Rochon',
            'So-Taro',
            'SS39',
            'Stacie Pitt',
            'Stanislav Sherbakov',
            'Stanton Feng',
            'Stella Spente',
            'Stepan Alekseev',
            'Stephanie Bouchard',
            'Stephanie Buscema',
            'Stephanie Law',
            'Stephanie Mitchell',
            'Stephan Martiniere',
            'Stephen Andrade',
            'Stephen Daniele',
            'Stephen L. Walsh',
            'Stephen Stark',
            'Stephen Tappin',
            'Steve Argyle',
            'Steve Ellis',
            'Steve Firchow',
            'Steve Luke',
            'Steve Morris',
            'Steven Belledin',
            'Steven Russell Black',
            'Steve Prescott',
            'Steve Sunu',
            'Steve White',
            'stoicHua',
            'Stuart Beel',
            'Stuart Griffin',
            'Sue Ellen Brown',
            'Sumie Okazu',
            'Sung Choi',
            'Sun Nan',
            'Susan Garfield',
            'Susan Van Camp',
            'Susumu Kuroi',
            'Suzanne Helmigh',
            'SUZHIHUI',
            'Svetlin Velinov',
            'Syd Mills',
            'Sydney Adams',
            'Sylvain Sarrailh',
            'Syutsuri',
            'Tada',
            'Takayuki Futami',
            'Takuma Ebisu',
            'Talia Armato-Helle',
            'Tang Xiaogu',
            'Tan Yan Yao',
            'TAPIOCA',
            'Tara Rueping',
            'Taras Susak',
            'Taro Yamazaki',
            'Tatamepi',
            'Tatiana Kirgetova',
            'Tatiana Veryayskaya',
            'Tatiana Vetrova',
            'Taylor Ingvarsson',
            'TCC',
            'Ted Galaday',
            'Ted Naifeh',
            'Teodora Dumitriu',
            'Terada Katsuya',
            'Terese Nielsen',
            'Terry Springer',
            'Tetsu Kurosawa',
            'Tetsuo Hara',
            'Thanh Tuấn',
            'Thea Dumitriu',
            'Theodoru',
            'Thomas Denmark',
            'Thomas Gianni',
            'Thomas Manning',
            'Thomas M. Baxa',
            'Thomas Ricci',
            'Thomas Roach',
            'Thomas Stoop',
            'Thomas Zenteno',
            'Tiago Sousa',
            'Tia Masic',
            'Tianhua X',
            'Tiffany Turrill',
            'Timba Smits',
            'Tim Brumley',
            'Tim Hildebrandt',
            'Tingting Yeh',
            'Titus Lunter',
            'TMRWLND',
            'Tobias Kwan',
            'Tobihachi',
            'Todd Lockwood',
            'TODEE',
            'Toma Feizo Gas',
            'Tomas Duchek',
            'Tomas Giorello',
            'Tomáš Honz',
            'Tomasz Jedruszek',
            'Tomasz Zarucki',
            'Tom Babbey',
            'Tomek Larek',
            'Tom Fleming',
            'Tom Kyffin',
            'Tommy Arnold',
            'TOMO77',
            'Tomohito',
            'Tom Roberts',
            'Tom Wänerstrand',
            'Tony Foti',
            'Tony Roberts',
            'Tony Szczudlo',
            'Toraji',
            'Torgeir Fjereide',
            'Torstein Nordstrand',
            'Toru Terada',
            'Toshiaki Takayama',
            'Totetsu Kondo',
            'Tran Nguyen',
            'Trashkittyart',
            'Trevor Claxton',
            'Trevor Hairsine',
            'Trick Jarrett',
            'Tripper Dungan',
            'Tristan Elwell',
            'Tsubonari',
            'Tsutomu Kawade',
            'TSWCK',
            'T-Track',
            'Tuan Duong Chu',
            'Tubaki Halsame',
            'Tuomas Korpi',
            'Tyler Crook',
            'Tyler Jacobson',
            'Tyler Smith',
            'Tyler Walpole',
            'Tyler Wright',
            'Tyukina Tatiana',
            'UDON',
            'Uichi Ukumo',
            'Ulrich Brunin',
            'Umiu Geso',
            'Una Fricker',
            'Uriah Voth',
            'Uros Sljivic',
            'Uta Natsume',
            'Uzhen Lin',
            'Vaigintas Pakenis',
            'Valera Lutfullina',
            'Vallez Gax',
            'Val Mayerik',
            'Vance Kelly',
            'Vance Kovacs',
            'Veli Nyström',
            'Véronique Chabot',
            'Véronique Meignaud',
            'Victor Adame Minguez',
            'Victor Harmatiuk',
            'Victoria Caña',
            'Victor Maury',
            'Victor Sales',
            'Viko Menezes',
            'Viktor Titov',
            'Vilhelmas Banys',
            'Villarrte',
            'Vincent Christiaens',
            'Vincent Evans',
            'Vincent Proce',
            'Vi Szendrey (Cashile)',
            'Vladimir Krisetskiy',
            'Volkan Baǵa',
            'Volta Creation',
            'Voyager Illustration',
            'Walleystation',
            'Wang Chuxiong',
            'Wang Feng',
            'Wangjie Li',
            'Wang Yuqun',
            'Warren Mahy',
            'Wayne England',
            'Wayne Reynolds',
            'Wayne Wu',
            'Wei Guan',
            'Wei Wei',
            'Wenfei Ye',
            'Wero Gallo',
            'Wesley Burt',
            'WFlemming Illustration',
            'Whit Brachna',
            'Willem Hampson',
            'Will Gist',
            'William Donohoe',
            'William O\'Connor',
            'William Phifer',
            'William Simpson',
            'William Tempest',
            'William Wu',
            'Willian Murai',
            'Will Liu',
            'Will Sweeney',
            'Winona Nelson',
            'Wisnu Tan',
            'Wizard of Barge',
            'Wojtek Łebski',
            'WolfSkullJack',
            'Wolk Sheep',
            'Wonchun Choi',
            'Wooden Cyclops',
            'Woonak',
            'Wylie Beckert',
            'Xabi Gaztelua',
            'Xavier Ribeiro',
            'Xiaji',
            'Xiaobotong',
            'XiaoDi Jin',
            'Xin-Yu Liu',
            'Xi Zhang',
            'Xu Tan',
            'Xu Xiaoming',
            'Yakotakos',
            'Yamada Rokkaku',
            'Yamamoto Akifumi',
            'Yang Guangmai',
            'Yang Hong',
            'Yang Jun Kwon',
            'Yang Luo',
            'Yangtian Li',
            'Yangyang',
            'Yan Li',
            'Yaomojun',
            'Yaya',
            'Yefim Kligerman',
            'Yeong-Hao Han',
            'Yigit Koroglu',
            'Yohann Schepacz',
            'Yoichi Ito',
            'Yoji Shinkawa',
            'Yokota Katsumi',
            'yo-ne',
            'Yongjae Choi',
            'Yoni Skolnik',
            'Yoroikoji',
            'Yoshimo',
            'Yoshino Himori',
            'Yoshiro Ambe',
            'Yoshitaka Amano',
            'Yoshiya',
            'Yoshi Yoshitani',
            'Yosuke Adachi',
            'Yosuke Ueno',
            'Yuchi Yuki',
            'Yuhki Takeuchi',
            'Yuichi Murakami',
            'Yuka Oka',
            'Yuka Sakuma',
            'Yukie Tajima',
            'Yuki Fujisawa',
            'Yukihiro Maruo',
            'Yu-ki Nishimoto',
            'Yuko Shimizu',
            'Yuliya Litvinova',
            'Yu Maeda',
            'Yumeko',
            'Yumi Ozuno',
            'Yunomachi',
            'Yuriy Chemezov',
            'Yusuke Katekari',
            'Yutaka Li',
            'Yuta Shimpo',
            'Yuumei',
            'Yuzushio',
            'YW Tang',
            'Zach Alexander',
            'Zach Francks',
            'Zack Stella',
            'Zak Plucinski',
            'Zara Alfonso',
            'Zara H',
            'Zbigniew M. Bielak',
            'Zeb Love',
            'Zezhou Chen',
            'Zhang Jiazhen',
            'Zhao Tan',
            'Zhillustrator',
            'Zina Saunders',
            'Zinna Du',
            'ZIUK',
            'zizero',
            'Zoltan Boros',
            'Zoran Cardula',
            'ZOUNOSE',
            'Zuzanna Wużyk',
            'コーヘー',
            '库雪明',
            '康羽',
            '张艺娜',
            '徐晓鸣',
            '李尤松',
            '李有良',
            '李铁',
            '杨光恒',
            '杨钊',
            '林玄泰',
            '王峰',
        ];

        foreach ($names as $name) {
            $artist = new EntityArtist();
            $artist->setName($name);
            $manager->persist($artist);
        }

        $manager->flush();
    }
}
